services:
  postgres:
    image: postgres:12
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: tekbetter
      POSTGRES_PASSWORD: example
      POSTGRES_DB: tekbetter
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  default:
    driver: bridge