version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  redis:
    image: redis:latest
    container_name: redis-tekbetter
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123456
    command: [ "redis-server", "--requirepass", "123456" ]
volumes:
  dbdata6:
